spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt_security
    username: alien
    password: alien@1974
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
app:
  jwt:
    secret.key: "28482B4D6251655468566D597133743677397A24432646294A404E635266556A"

# ===============================
# = LOGGING
# ===============================
#logging.config=file:src/main/resources/logback-default.xml
logging:
  level:
    root: info
    edu.security.jwt: debug
    org.hibernate: error
    org.hibernate.persister.entity: error
